DATASET: gvqa
NUM_DEVICES: 8
MODEL:
  TYPE: VGG16_reldn_fast_rcnn_conv4_spo_for_p
  SUBTYPE: embd_fusion_w_relu_yall
  SPECS: 8gpus_vgg16_softmax_no_last_l2norm_trainval_w_cluster_2_lan_layers_memory_sbj_obj_fusion_v3
  LOSS_TYPE: SOFTMAX  # EUC, SOFTMAX
  MODEL_NAME: VGG16_rel_softmax
  BN_MOMENTUM: 0.9
  BN_EPSILON: 1.0000001e-5
  FC_INIT_STD: 0.01
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  WEAK_LABELS: False
  NUM_WEAK_LABELS: 0
  NUM_CLASSES_SBJ_OBJ: 1703
  NUM_CLASSES_PRD: 310
  MEMORY_MODULE_FUSION: True
  MEMORY_MODULE_SBJ_OBJ: True
  MEMORY_MODULE_PRD: False
  COSNORM: False
  ATTENTION: True
  REACHABILITY: True
VISUAL_EMBEDDING:
  WEIGHT_SHARING:  SBJ_OBJ_SHARED #, all_unshared,  sbj_obj_shared, all_unshared
  L2_NORMALIZE: True
TEXT_EMBEDDING:
  HIDDEN_LAYERS: 2  # 1, 0
  L2_NORMALIZE: True
INPUT_LANG_EMBEDDING_DIM: 600
OUTPUT_EMBEDDING_DIM: 1024
TRAIN:
  PARAMS_FILE: datasets/large_scale_VRD/coco_models/softmax_baseline_retrain_plus_centroids_raw.pkl
  #PARAMS_FILE: datasets/large_scale_VRD/coco_models/softmax_baseline_plus_centroids_raw.pkl
  #PARAMS_FILE: datasets/large_scale_VRD/coco_models/softmax_baseline_plus_centroids.pkl
  #PARAMS_FILE: datasets/large_scale_VRD/coco_models/vgg16_model_final_plus_centroids.pkl
  #PARAMS_FILE: datasets/large_scale_VRD/coco_models/vgg16_model_final.pkl
  #PARAMS_FILE: checkpoints/gvqa/VGG16_reldn_fast_rcnn_conv4_spo_for_p/embd_fusion_w_relu_yall/8gpus_vgg16_softmaxed_triplet_no_last_l2norm_trainval_w_cluster_2_lan_layers/train/best.pkl
  DATA_TYPE: train
  BBOX_REG: False
  BBOX_NORMALIZE_TARGETS: False  # No bbox regression at the end
  USE_FLIPPED: True
  BATCH_SIZE_PER_IM: 128
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  # SCALE_JITTER_TYPE: googleNet
  EVALUATION_FREQUENCY: 25000 # 2500  # 50000
TEST:
  WEIGHTS: checkpoints/gvqa/VGG16_reldn_fast_rcnn_conv4_spo_for_p/embd_fusion_w_relu_yall/8gpus_vgg16_softmax_no_last_l2norm_trainval_w_cluster_2_lan_layers_memory_sbj_obj_fusion_v3/train/best.pkl
  DATA_TYPE: test
  PROPOSAL_FILE: datasets/large_scale_VRD/proposals/gvqa/gt_proposals_test.pkl
  BBOX_REG: False
  ISA: False
SOLVER:
  BASE_LR: 0.0001
  STEP_SIZES: [125000]
  NUM_ITERATIONS: 175000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  GAMMA: 0.1
  NESTEROV: True
  WARM_UP_ITERS: 500  # 10000
  WARM_UP_LR: 0.0001
CHECKPOINT:
  CHECKPOINT_PERIOD: 10000
