DATASET: vg_wiki_and_relco
NUM_DEVICES: 8
RANDOM_SEED: 0
MODEL:
  TYPE: VGG16_reldn_fast_rcnn_conv4_spo_for_p
  SUBTYPE: embd_fusion_w_relu_yall
  SPECS: 8gpus_vgg16_softmaxed_triplet_no_last_l2norm_trainval_w_cluster_2_lan_layers_hubness10
  LOSS_TYPE: SOFTMAXED_TRIPLET  # EUC, SOFTMAX
  MODEL_NAME: VGG16_rel_softmaxed_triplet
  BN_MOMENTUM: 0.9
  BN_EPSILON: 1.0000001e-5
  FC_INIT_STD: 0.01
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  NUM_CLASSES_SBJ_OBJ: 53304
  NUM_CLASSES_PRD: 29086
VISUAL_EMBEDDING:
  WEIGHT_SHARING:  SBJ_OBJ_SHARED #, all_unshared,  sbj_obj_shared, all_unshared
  L2_NORMALIZE: True
TEXT_EMBEDDING:
  HIDDEN_LAYERS: 2  # 1, 0
  L2_NORMALIZE: True
INPUT_LANG_EMBEDDING_DIM: 600
OUTPUT_EMBEDDING_DIM: 1024
TRAIN:
  PARAMS_FILE: datasets/large_scale_VRD/coco_models/vgg16_model_final.pkl
  DATA_TYPE: train
  BBOX_REG: False
  BBOX_NORMALIZE_TARGETS: False  # No bbox regression at the end
  USE_FLIPPED: True
  HUBNESS: True
  HUBNESS_scale: 10.0
  BATCH_SIZE_PER_IM: 128
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  # SCALE_JITTER_TYPE: googleNet
  EVALUATION_FREQUENCY: 2500  # 50000
TEST:
  WEIGHTS: checkpoints/vg_wiki_and_relco/VGG16_reldn_fast_rcnn_conv4_spo_for_p/embd_fusion_w_relu_yall/8gpus_vgg16_softmaxed_triplet_no_last_l2norm_trainval_w_cluster_2_lan_layers_hubness10/train/latest.pkl #checkpoints/vg_wiki_and_relco/latest_final.pkl
  DATA_TYPE: val
  PROPOSAL_FILE: datasets/large_scale_VRD/proposals/vg/gt_proposals_test.pkl
  BBOX_REG: False
SOLVER:
  BASE_LR: 0.001
  STEP_SIZES: [125000]
  NUM_ITERATIONS: 275000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  GAMMA: 0.1
  NESTEROV: True
  WARM_UP_ITERS: 500  # 10000
  WARM_UP_LR: 0.0001
CHECKPOINT:
  CHECKPOINT_PERIOD: 25000
